<a href="https://colab.research.google.com/github/DivakarSingh1245/DivakarSingh1245/blob/main/Numpy_totorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr= np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
print('Hii I am Divakar')

Hii I am Divakar


In [ ]:
arr1 = np.array([[1,2,4,5],[3,4,6,7]])
print(arr1)
print(type(arr1))

[[1 2 4 5]
 [3 4 6 7]]
<class 'numpy.ndarray'>


In [ ]:
arr3 = np.array([[[12,13,14],[12,62,34],[45,46,37]]])
print(arr3)
print(type(arr3))

[[[12 13 14]
  [12 62 34]
  [45 46 37]]]
<class 'numpy.ndarray'>


### Shape and Size of array

In [ ]:
print(arr1.shape)
print(arr1.size)
print(arr1.ndim)

(2, 4)
8
2


#creating special array


In [ ]:
Zeros = np.zeros((3,3))
ones = np.ones((2,2))
identity = np.eye(3)
random_array = np.random.rand(3,3)
print(Zeros)
print(ones)
print(random_array)
print(identity)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[0.25052474 0.26165313 0.26906977]
 [0.51474137 0.34197884 0.86910064]
 [0.20100938 0.56943521 0.56417123]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


mathmatical opration of array


In [ ]:
arr = np.array([10,20,30,40])
print(arr+5)
print(arr*2)

print(np.sqrt(arr))
print(np.mean(arr))
print(np.std(arr))

[15 25 35 45]
[20 40 60 80]
[3.16227766 4.47213595 5.47722558 6.32455532]
25.0
11.180339887498949


indexing and slicing in array

In [ ]:
# accessing a single element
arr= np.array([10,20,30,40,50])

print(arr[2])
print(arr[-1])

30
50


In [ ]:
# sllicing of array(extrating of a part of element )

print(arr[2:4])
print(arr[:2])
print(arr[::3])

[30 40]
[10 20]
[10 40]


Slicing in 2d array

In [ ]:
arr = np.array([[12,13,14],[16,17,18],[23,24,25]])
print(arr)
print(arr[0,2])
print(arr[1:,2])

[[12 13 14]
 [16 17 18]
 [23 24 25]]
14
[18 25]


In [ ]:
# filtering array with condition
arr= np.array([10,20,30,40,50])
print(arr>20)
print(arr %20 == 0)

[False False  True  True  True]
[False  True False  True False]


In [ ]:
# matrix operation in numpy

# Adding two matrices

arr1 = np.array([[12,13,14],[23,34,25]])
arr2 = np.array([[34,35,36,],[45,46,47]])

print(arr1+arr2)

print(arr1*arr2)

[[46 48 50]
 [68 80 72]]
[[ 408  455  504]
 [1035 1564 1175]]


In [ ]:
import pandas as pd

data = np.array([[1,'A'],[2,'B'],[3,'c']])
df= pd.DataFrame(data,columns = ['ID','Category'])
print(df)

  ID Category
0  1        A
1  2        B
2  3        c


# Numpy project

In [ ]:
import numpy as np  # Importing NumPy library

# Creating a dataset using NumPy array
data = np.array([
    [101, 15, 5, 25],   # Player 1 (Player ID: 101)
    [102, 10, 7, 30],   # Player 2 (Player ID: 102)
    [103, 25, 10, 28],  # Player 3 (Player ID: 103)
    [104, 5, 2, 20],    # Player 4 (Player ID: 104)
    [105, 18, 9, 27]    # Player 5 (Player ID: 105)
])

print("Player Data:\n", data)


Player Data:
 [[101  15   5  25]
 [102  10   7  30]
 [103  25  10  28]
 [104   5   2  20]
 [105  18   9  27]]


In [ ]:
goals= data[:,1]
print("Goals:",goals)
assists = data[:,2]
matches= data[:,3]
print("assists:",assists)
print('matches:',matches)



Goals: [15 10 25  5 18]
assists: [ 5  7 10  2  9]
matches: [25 30 28 20 27]


In [ ]:
#calculate average goals and assists

avg_goals = np.mean(goals)
print(avg_goals)

avg_asssists = np.mean(assists)
print(avg_asssists)

14.6
6.6


In [ ]:
# finding top goals scorers

top_goals = data[data[:,1] >15]
print(top_goals)



[[103  25  10  28]
 [105  18   9  27]]


In [ ]:
topgoals = goals>15
print(topgoals)

[False False  True False  True]


In [ ]:
# calculate goals per match by each player

goals_per_match = goals/matches
print(goals_per_match)



[0.6        0.33333333 0.89285714 0.25       0.66666667]


In [ ]:
#high assests player

high_assests_player= data[data[:,2]>5]
print(high_assests_player)

[[102  10   7  30]
 [103  25  10  28]
 [105  18   9  27]]
